cora:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 1500
  max_epoch_f: 300
  mask_rate: 0.5
  num_layers: 2
  encoder: gat
  decoder: gat 
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce 
  drop_edge_rate: 0.0
  optimizer: adam
  #replace_rate: 0.05 
  replace_rate: 0.00
  alpha_l: 3
  scheduler: True
citeseer:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 2
  num_layers: 2
  weight_decay: 2e-5
  weight_decay_f: 0.01
  max_epoch: 300
  max_epoch_f: 300
  mask_rate: 0.5
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2  
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.1
  alpha_l: 1 # or 3 
  scheduler: True
coaphoto:
  lr: 0.0011
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 2
  num_out_heads: 1
  num_layers: 1
  num_d_layers: 2
  weight_decay: 0
  weight_decay_f: 0
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 620
  max_epoch_f: 300
  mask_rate: 0.1
  encoder: gcn
  decoder: gat
  discrimator: gcn
  activation: prelu  
  linear_prob: True
  loss_fn: sce 
  drop_edge_rate: 0.0
  optimizer: adamw
  d_optimizer: adamw
  replace_rate: 0.1
  alpha_l: 3
  alpha: 2.5
  beta: 1
  gamma: 1
  attn_drop: 0.8
  attn_drop_d: 0.1
  in_drop: 0.6
  in_drop_d: 0.6
  scheduler: True
  dim_norm: 1
  recon_norm: 1  
pubmed:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 2
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 1000
  max_epoch_f: 300
  mask_rate: 0.75
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 3
  scheduler: True


